name: Update Packagist

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist Update
        run: |
          curl -XPOST -H "Authorization: Bearer ${{ secrets.PACKAGIST_TOKEN }}" \
               https://packagist.org/api/update-package/?username=${{ secrets.PACKAGIST_USERNAME }}&repository=${{ github.repository }}

      - name: Notify Success
        if: success()
        run: echo "Packagist update triggered successfully."

      - name: Notify Failure
        if: failure()
        run: echo "Failed to trigger Packagist update."
