name: Update Packagist

# Trigger the workflow on push to master branch
on:
  push:
    branches:
      - master

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Send update request to Packagist
      - name: Update Packagist
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -u "$PACKAGIST_USERNAME:$PACKAGIST_TOKEN" \
            -d '{"repository":{"url":"https://github.com/${{ github.repository }}"}}' \
            "https://packagist.org/api/update-package?username=$PACKAGIST_USERNAME&apiToken=$PACKAGIST_TOKEN"
